orbs:
  gradle: circleci/gradle@2.2.0
  aws-ecr: circleci/aws-ecr@6.12.2
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
              # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle build
      - store_artifacts:
          path: build/libs/
          destination: build/libs/

workflows:
  checkout-build-test-deploy:
    jobs:
      - gradle/test
      - build:
          requires:
            - gradle/test
      - aws-ecr/build-and-push-image:
          repo: "hellospringcircle"
          tag: "latest"
          requires:
            - build