orbs:
  gradle: circleci/gradle@2.2.0
  aws-ecr: circleci/aws-ecr@6.12.2
  aws-ecs: circleci/aws-ecs@1.3.0
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
              # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run: gradle build
      - persist_to_workspace:
          root: build/libs
          paths: hellospringcircle-1.0.jar

workflows:
  checkout-build-test-deploy:
    jobs:
      - gradle/test
      - build:
          requires:
            - gradle/test
      - aws-ecr/build-and-push-image:
          name: push-image-to-ecr
          repo: "hellospringcircle"
          tag: "latest"
          attach-workspace: true
          workspace-root: build/libs
          requires:
            - build
      - aws-ecs/deploy-service-update:
          name: deploy-development
          requires:
            - push-image-to-ecr
          family: "hsc-task-definition"
          cluster-name: "hsc-cluster"
          service-name: "hsc-service"
          container-image-name-updates: "hsc-container,tag=latest"